plugins {
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.20'
}

version = "${mod_version}"
group = "${mod_group_id}"

base {
    archivesName = "${modid}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.modid
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.modid
        argument '--nogui'
    }
}

repositories {
    maven {
        url = "https://maven.maxanier.de/releases"
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    compileOnly "curse.maven:parcool-482378:${parcool}"
    compileOnly "curse.maven:glitchcore-955399:5660740"
    compileOnly "curse.maven:tough-as-nails-246391:5833252"
    compileOnly "de.teamlapen.vampirism:Vampirism:1.21-1.10.7:api"
    compileOnly "curse.maven:vampirism-become-a-vampire-233029:6544569"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            modid                  : modid,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
